const SUPABASE_URL="https://ajxcdgneroabkgoufjor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_KGN1SeLryFEg9n9iaoxAag_s2OuqeFJ";
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const OLD_STORAGE_KEYS=["hkstp-key-desk-v3","hkstp-key-desk-v2","hkstp-key-desk-v1"];
const FLOOR_TAGS=["通匙","B/F","G/F","1/F","2/F","3/F","4/F","5/F","6/F","R/F"],norm=v=>String(v??"").toLocaleLowerCase("zh-HK").replace(/\s+/g,"");
const FLOOR_SEARCH_TAGS=new Set(FLOOR_TAGS.filter(x=>x!=="通匙").map(norm)),colorMap={黑色:"#252b31",粉紅色:"#ee78a6",黃色:"#f1c62f",藍色:"#3488d1",紅色:"#e14b4b",綠色:"#27a86d",無:"#d7e1e6",其他:"#9b72cf"};
const el=id=>document.getElementById(id);let keys=[],activeFilter="all",searchTags=[],purposeTags=[],currentUserId=null,realtimeChannel=null,primarySort="color-asc",secondarySort="number-asc";
document.head.insertAdjacentHTML("beforeend","<style>[hidden]{display:none!important}</style>");
document.head.insertAdjacentHTML("beforeend","<style>.form-grid textarea{min-height:86px;resize:vertical;border:1px solid #bcccdc;border-radius:8px;padding:10px 11px;background:#fff;font:inherit}.notes-text{white-space:pre-wrap;overflow-wrap:anywhere;color:#486581;font-weight:500!important}</style>");
const grid=el("keyGrid"),template=el("keyCardTemplate"),dialog=el("keyDialog"),form=el("keyForm");
const filterGroup=document.createElement("div"),filtersNode=document.querySelector(".filters");filterGroup.className="filter-sort-group";filtersNode.before(filterGroup);filterGroup.append(filtersNode);filterGroup.insertAdjacentHTML("beforeend",'<div class="sort-panel"><label><span>主要排序</span><select id="primarySort"><option value="number-asc">編號：升序</option><option value="number-desc">編號：降序</option><option value="purpose-asc">用途：升序</option><option value="purpose-desc">用途：降序</option><option value="color-asc" selected>顏色：升序</option><option value="color-desc">顏色：降序</option></select></label><label><span>次要排序</span><select id="secondarySort"><option value="none">不使用</option><option value="number-asc" selected>編號：升序</option><option value="number-desc">編號：降序</option><option value="purpose-asc">用途：升序</option><option value="purpose-desc">用途：降序</option><option value="color-asc">顏色：升序</option><option value="color-desc">顏色：降序</option></select></label></div>');
document.head.insertAdjacentHTML("beforeend","<style>.filter-sort-group{display:flex;flex-direction:column;gap:8px}.sort-panel{display:grid;grid-template-columns:1fr 1fr;gap:8px}.sort-panel label{display:flex;flex-direction:column;gap:4px;color:#627d98;font-size:11px;font-weight:800}.sort-panel select{height:38px;border:1px solid #bcccdc;border-radius:8px;padding:0 28px 0 9px;background:#fff;color:#334e68;font-size:12px;font-weight:700}@media(max-width:700px){.sort-panel{grid-template-columns:1fr 1fr}.filter-sort-group{width:100%}}</style>");
el("floorOptions").closest("fieldset").insertAdjacentHTML("beforebegin",'<label class="wide">備注（選填）<textarea id="keyNotes" maxlength="500" placeholder="可留空"></textarea></label>');
template.content.querySelector("dl").insertAdjacentHTML("beforeend",'<div class="notes-row" hidden><dt>備注</dt><dd class="notes-text"></dd></div>');

function setAuthMessage(message,success=false){const node=el("authMessage");node.textContent=message;node.classList.toggle("success",success)}
function setSync(message,state=""){el("syncStatus").textContent=message;el("syncStatus").parentElement.className=`sync-bar ${state}`.trim()}
function setBusy(busy){document.body.classList.toggle("is-busy",busy)}
function withTimeout(promise,ms,message){return Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(message)),ms))])}
function isManageView(){return new URLSearchParams(location.search).get("view")==="manage"}
function goToManage(){const url=new URL(location.href);url.search="?view=manage";url.hash="";location.replace(url)}
function goToLogin(){const url=new URL(location.href);url.search="";url.hash="";location.replace(url)}

async function handleSession(session){
  if(!session){currentUserId=null;if(isManageView()){goToLogin();return}el("authScreen").hidden=false;el("authScreen").style.display="";el("appShell").hidden=true;return}
  if(!isManageView()){goToManage();return}
  if(currentUserId===session.user.id)return;
  setBusy(true);
  try{
    setAuthMessage("正在驗證帳戶…",true);
    const {data:allowed,error}=await withTimeout(db.rpc("is_allowed_user"),12000,"連線逾時，請檢查網絡後再試。");
    if(error)throw error;
    if(!allowed){await db.auth.signOut();setAuthMessage("此電郵帳戶未獲批准使用本系統。請聯絡管理員。");return}
    currentUserId=session.user.id;el("userEmail").textContent=session.user.email;el("authScreen").hidden=true;el("authScreen").style.display="none";el("appShell").hidden=false;
    await withTimeout(loadCloudKeys(true),15000,"讀取鎖匙資料逾時，請重新整理頁面。");
    subscribeToChanges();setAuthMessage("");
  }catch(error){
    currentUserId=null;el("authScreen").hidden=false;el("appShell").hidden=true;
    setAuthMessage(`登入未完成：${error?.message||"未知錯誤"}`);
  }finally{setBusy(false)}
}

async function loadCloudKeys(allowMigration=false){
  setSync("正在同步雲端資料…","syncing");
  const {data,error}=await db.from("keys").select("*").order("created_at",{ascending:true});
  if(error){setSync(`同步失敗：${error.message}`,"error");return}
  keys=(data||[]).map(mapDbRecord);
  if(!keys.length&&allowMigration){const local=readLocalKeys();if(local.length){await importLocalKeys(local);return}}
  render();setSync("已同步雲端資料庫");
}

function mapDbRecord(r){return{id:r.id,color:r.color,purposes:r.purposes||[],number:r.number,building:r.building,block:r.block||"無",floors:r.floors||[],notes:r.notes||"",borrowed:r.borrowed,created_at:r.created_at}}
function toDbRecord(r){return{color:r.color,purposes:r.purposes,number:r.number,building:r.building,block:r.block,floors:r.floors,notes:r.notes||"",borrowed:r.borrowed}}
function migrateLocal(r){let floors=r.floors;if(!Array.isArray(floors)){const s=String(r.location||"").replace(/&/g,"／");floors=FLOOR_TAGS.filter(x=>norm(s).includes(norm(x)));floors=floors.includes("通匙")?["通匙"]:floors.length?floors:["通匙"]}let purposes=r.purposes;if(!Array.isArray(purposes))purposes=String(r.purpose||"").split(/[／/、,，]+/).map(x=>x.trim()).filter(Boolean);return{color:r.color||"其他",purposes:purposes.length?purposes:["未分類"],number:String(r.number||""),building:r.building||"2E",block:["Core 1","Core 2"].includes(r.block)?r.block:"無",floors,notes:String(r.notes||""),borrowed:!!r.borrowed}}
function readLocalKeys(){for(const name of OLD_STORAGE_KEYS){try{const value=JSON.parse(localStorage.getItem(name));if(Array.isArray(value)&&value.length)return value.map(migrateLocal)}catch{}}return[]}
async function importLocalKeys(records){setSync("正在把舊紀錄遷移到雲端…","syncing");const {error}=await db.from("keys").insert(records.map(toDbRecord));if(error){setSync(`遷移失敗：${error.message}`,"error");return}OLD_STORAGE_KEYS.forEach(k=>localStorage.removeItem(k));await loadCloudKeys(false);setSync(`已遷移 ${records.length} 項紀錄到雲端`) }
function subscribeToChanges(){if(realtimeChannel)db.removeChannel(realtimeChannel);realtimeChannel=db.channel("keys-live").on("postgres_changes",{event:"*",schema:"public",table:"keys"},()=>loadCloudKeys(false)).subscribe()}

function keyMatchesTag(k,t){const n=norm(t);if(FLOOR_SEARCH_TAGS.has(n)&&k.floors.includes("通匙"))return true;return[k.color,k.number,k.building,k.block,...k.purposes,...k.floors].some(v=>norm(v).includes(n))}function matches(k){return searchTags.every(t=>keyMatchesTag(k,t))}
function makeRemovableChip(tag,onRemove){const b=document.createElement("button");b.type="button";b.className="search-chip";const s=document.createElement("span");s.textContent=tag;const x=document.createElement("b");x.textContent="×";b.append(s,x);b.onclick=onRemove;return b}
function renderSearchTags(){const c=el("searchTags");c.replaceChildren();searchTags.forEach((t,i)=>c.append(makeRemovableChip(t,()=>{searchTags.splice(i,1);render()})));el("clearSearch").hidden=!searchTags.length}function addSearchTag(){const i=el("searchInput");i.value.split(/[,，]+/).map(x=>x.trim()).filter(Boolean).forEach(t=>{if(!searchTags.some(x=>norm(x)===norm(t)))searchTags.push(t)});i.value="";render()}
function renderPurposeTags(){const c=el("purposeTags");c.replaceChildren();purposeTags.forEach((t,i)=>c.append(makeRemovableChip(t,()=>{purposeTags.splice(i,1);renderPurposeTags()})));el("purposeError").hidden=!!purposeTags.length}function addPurposeTag(){const i=el("purposeInput");i.value.split(/[,，／/、]+/).map(x=>x.trim()).filter(Boolean).forEach(t=>{if(!purposeTags.some(x=>norm(x)===norm(t)))purposeTags.push(t)});i.value="";renderPurposeTags()}
function compareByRule(a,b,rule){if(rule==="none")return 0;const [field,direction]=rule.split("-"),sign=direction==="desc"?-1:1;if(field==="number")return sign*String(a.number).localeCompare(String(b.number),"zh-HK",{numeric:true,sensitivity:"base"});if(field==="purpose")return sign*(a.purposes||[]).join("、").localeCompare((b.purposes||[]).join("、"),"zh-HK",{numeric:true,sensitivity:"base"});const colorOrder=["黑色","粉紅色","黃色","藍色","紅色","綠色","無","其他"],ai=colorOrder.indexOf(a.color),bi=colorOrder.indexOf(b.color);return sign*((ai<0?colorOrder.length:ai)-(bi<0?colorOrder.length:bi))}function compareKeys(a,b){return compareByRule(a,b,primarySort)||compareByRule(a,b,secondarySort)}
function render(){const f=keys.filter(k=>matches(k)&&(activeFilter==="all"||(activeFilter==="borrowed")===k.borrowed)).sort(compareKeys);grid.replaceChildren();f.forEach(k=>grid.append(createCard(k)));renderSearchTags();el("totalCount").textContent=keys.length;el("availableCount").textContent=keys.filter(k=>!k.borrowed).length;el("borrowedCount").textContent=keys.filter(k=>k.borrowed).length;el("resultNote").textContent=searchTags.length||activeFilter!=="all"?`找到 ${f.length} 項相符紀錄`:`現有 ${keys.length} 項鎖匙紀錄`;el("emptyState").hidden=!!f.length}
function addDataChips(target,values){values.forEach(v=>{const s=document.createElement("span");s.className="data-chip";s.textContent=v;target.append(s)})}
function createCard(k){const c=template.content.firstElementChild.cloneNode(true);c.classList.toggle("is-borrowed",k.borrowed);c.querySelector(".color-dot").style.background=colorMap[k.color]||colorMap.其他;c.querySelector(".building").textContent=`${k.building} 大樓`;c.querySelector(".block-name").textContent=`· ${k.block}`;c.querySelector(".number").textContent=k.number;c.querySelector(".status-pill").textContent=k.borrowed?"已借出":"未借出";addDataChips(c.querySelector(".purpose-list"),k.purposes);addDataChips(c.querySelector(".floor-list"),k.floors);const notesRow=c.querySelector(".notes-row");if(k.notes){notesRow.hidden=false;notesRow.querySelector(".notes-text").textContent=k.notes}const b=c.querySelector(".status-action");b.textContent=k.borrowed?"✓ 標記為已歸還":"→ 標記為已借出";b.classList.add(k.borrowed?"btn-success":"btn-warning");b.onclick=()=>toggleBorrowed(k,b);c.querySelector(".edit-action").onclick=()=>openForm(k);c.querySelector(".delete-action").onclick=()=>confirmDelete(k);return c}
async function toggleBorrowed(k,button){button.disabled=true;setSync("正在儲存狀態…","syncing");const {error}=await db.from("keys").update({borrowed:!k.borrowed}).eq("id",k.id);if(error){setSync(`儲存失敗：${error.message}`,"error");button.disabled=false;return}await loadCloudKeys(false)}

function buildFloorOptions(selected=[]){const c=el("floorOptions");c.replaceChildren();FLOOR_TAGS.forEach(f=>{const l=document.createElement("label");l.className="floor-tag";const i=document.createElement("input");i.type="checkbox";i.value=f;i.checked=selected.includes(f);i.onchange=()=>{const a=[...c.querySelectorAll("input")];if(f==="通匙"&&i.checked)a.filter(x=>x!==i).forEach(x=>x.checked=false);if(f!=="通匙"&&i.checked)a.find(x=>x.value==="通匙").checked=false;updateFloorStyles();el("floorError").hidden=true};l.append(i,document.createTextNode(f));c.append(l)});updateFloorStyles()}function updateFloorStyles(){document.querySelectorAll(".floor-tag").forEach(l=>l.classList.toggle("selected",l.querySelector("input").checked))}function selectedFloors(){return[...el("floorOptions").querySelectorAll("input:checked")].map(i=>i.value)}
function openForm(k=null){el("dialogTitle").textContent=k?"編輯鎖匙":"新增鎖匙";el("keyId").value=k?.id||"";el("tagColor").value=k?.color||"黑色";el("keyNumber").value=k?.number||"";el("building").value=k?.building||"";el("block").value=["Core 1","Core 2"].includes(k?.block)?k.block:"無";el("keyNotes").value=k?.notes||"";purposeTags=[...(k?.purposes||[])];renderPurposeTags();buildFloorOptions(k?.floors||[]);el("floorError").hidden=true;el("saveError").hidden=true;dialog.showModal();setTimeout(()=>el("keyNumber").focus(),0)}function closeForm(){dialog.close();form.reset();purposeTags=[]}
function confirmDelete(k){const d=el("confirmDialog");el("confirmText").textContent=`將永久刪除 ${k.building} 大樓 ${k.block} #${k.number}。此動作無法還原。`;d.showModal();d.addEventListener("close",async()=>{if(d.returnValue==="confirm"){setSync("正在刪除紀錄…","syncing");const {error}=await db.from("keys").delete().eq("id",k.id);if(error)setSync(`刪除失敗：${error.message}`,"error");else await loadCloudKeys(false)}},{once:true})}

form.addEventListener("submit",async e=>{e.preventDefault();if(el("purposeInput").value.trim())addPurposeTag();if(!form.reportValidity())return;const floors=selectedFloors();if(!purposeTags.length){el("purposeError").hidden=false;return}if(!floors.length){el("floorError").hidden=false;return}const id=el("keyId").value,record={color:el("tagColor").value,number:el("keyNumber").value.trim(),purposes:[...purposeTags],building:el("building").value,block:el("block").value,floors,notes:el("keyNotes").value.trim(),borrowed:keys.find(k=>k.id===id)?.borrowed||false};el("saveKeyBtn").disabled=true;const query=id?db.from("keys").update(record).eq("id",id):db.from("keys").insert(record);const {error}=await query;el("saveKeyBtn").disabled=false;if(error){el("saveError").textContent=`儲存失敗：${error.message}`;el("saveError").hidden=false;return}closeForm();await loadCloudKeys(false)});

el("authForm").addEventListener("submit",async e=>{e.preventDefault();setBusy(true);setAuthMessage("正在登入…",true);try{const {data,error}=await withTimeout(db.auth.signInWithPassword({email:el("authEmail").value.trim(),password:el("authPassword").value}),12000,"連線逾時，請稍後再試。");if(error)throw error;if(!data.session)throw new Error("未能建立登入狀態，請再試一次。");await handleSession(data.session)}catch(error){setAuthMessage(`登入失敗：${error?.message||"未知錯誤"}`)}finally{setBusy(false)}});
el("signUpBtn").onclick=async()=>{if(!el("authForm").reportValidity())return;setAuthMessage("正在建立帳戶…",true);const {data,error}=await db.auth.signUp({email:el("authEmail").value.trim(),password:el("authPassword").value,options:{emailRedirectTo:"https://delphi-spirit.github.io/"}});const exists=!error&&data?.user&&Array.isArray(data.user.identities)&&data.user.identities.length===0;if(exists||error&&/already|registered|exists/i.test(error.message)){setAuthMessage("該用戶已存在");return}if(error){setAuthMessage(`建立失敗：${error.message}`);return}if(data.session)await handleSession(data.session);else setAuthMessage("帳戶已建立，請到電郵信箱確認後再登入。",true)};
el("signOutBtn").onclick=async()=>{await db.auth.signOut();goToLogin()};el("addKeyBtn").onclick=()=>openForm();el("closeDialogBtn").onclick=closeForm;el("cancelBtn").onclick=closeForm;el("clearSearch").onclick=()=>{searchTags=[];render()};
el("primarySort").addEventListener("change",e=>{primarySort=e.target.value;render()});el("secondarySort").addEventListener("change",e=>{secondarySort=e.target.value;render()});
el("searchInput").addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===","){e.preventDefault();addSearchTag()}else if(e.key==="Backspace"&&!e.currentTarget.value&&searchTags.length){searchTags.pop();render()}});el("purposeInput").addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===","){e.preventDefault();addPurposeTag()}else if(e.key==="Backspace"&&!e.currentTarget.value&&purposeTags.length){purposeTags.pop();renderPurposeTags()}});el("purposeInput").addEventListener("blur",()=>{if(el("purposeInput").value.trim())addPurposeTag()});document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));render()});

db.auth.onAuthStateChange((event,session)=>{if(event==="SIGNED_OUT"){currentUserId=null;el("appShell").hidden=true;if(isManageView())goToLogin();else{el("authScreen").hidden=false;el("authScreen").style.display=""}}else if(session)setTimeout(()=>handleSession(session),0)});
db.auth.getSession().then(({data})=>handleSession(data.session));
