const STORAGE_KEY="hkstp-key-desk-v3",PREVIOUS_KEYS=["hkstp-key-desk-v2","hkstp-key-desk-v1"];
const FLOOR_TAGS=["通匙","B/F","G/F","1/F","2/F","3/F","4/F","5/F","6/F","R/F"],norm=v=>String(v??"").toLocaleLowerCase("zh-HK").replace(/\s+/g,"");
const FLOOR_SEARCH_TAGS=new Set(FLOOR_TAGS.filter(x=>x!=="通匙").map(norm)),colorMap={黑色:"#252b31",粉紅色:"#ee78a6",黃色:"#f1c62f",藍色:"#3488d1",紅色:"#e14b4b",綠色:"#27a86d",無:"#d7e1e6",其他:"#9b72cf"};
const seedKeys=[{id:crypto.randomUUID(),color:"紅色",purposes:["風櫃房","空調機房"],number:"113",building:"2E",block:"Core 1",floors:["R/F"],borrowed:false},{id:crypto.randomUUID(),color:"藍色",purposes:["垃圾房"],number:"63",building:"3E",block:"Core 1",floors:["G/F"],borrowed:true},{id:crypto.randomUUID(),color:"黃色",purposes:["消防控制室"],number:"113",building:"1W",block:"Core 2",floors:["通匙"],borrowed:false}];
const el=id=>document.getElementById(id);let keys=loadKeys(),activeFilter="all",searchTags=[],purposeTags=[];const grid=el("keyGrid"),template=el("keyCardTemplate"),dialog=el("keyDialog"),form=el("keyForm");
function migrate(r){let floors=r.floors;if(!Array.isArray(floors)){const s=String(r.location||"").replace(/&/g,"／");floors=FLOOR_TAGS.filter(x=>norm(s).includes(norm(x)));floors=floors.includes("通匙")?["通匙"]:floors.length?floors:["通匙"]}let purposes=r.purposes;if(!Array.isArray(purposes))purposes=String(r.purpose||"").split(/[／/、,，]+/).map(x=>x.trim()).filter(Boolean);const block=["Core 1","Core 2"].includes(r.block)?r.block:"無";return{...r,floors,purposes:purposes.length?purposes:["未分類"],block}}
function loadKeys(){try{const current=JSON.parse(localStorage.getItem(STORAGE_KEY));if(Array.isArray(current))return current.map(migrate);for(const name of PREVIOUS_KEYS){const old=JSON.parse(localStorage.getItem(name));if(Array.isArray(old))return old.map(migrate)}}catch{}return seedKeys}function saveKeys(){localStorage.setItem(STORAGE_KEY,JSON.stringify(keys))}
function keyMatchesTag(k,t){const n=norm(t);if(FLOOR_SEARCH_TAGS.has(n)&&k.floors.includes("通匙"))return true;return[k.color,k.number,k.building,k.block,...k.purposes,...k.floors].some(v=>norm(v).includes(n))}function matches(k){return searchTags.every(t=>keyMatchesTag(k,t))}
function makeRemovableChip(tag,onRemove){const b=document.createElement("button");b.type="button";b.className="search-chip";const s=document.createElement("span");s.textContent=tag;const x=document.createElement("b");x.textContent="×";b.append(s,x);b.onclick=onRemove;return b}
function renderSearchTags(){const c=el("searchTags");c.replaceChildren();searchTags.forEach((t,i)=>c.append(makeRemovableChip(t,()=>{searchTags.splice(i,1);render()})));el("clearSearch").hidden=!searchTags.length}function addSearchTag(){const i=el("searchInput");i.value.split(/[,，]+/).map(x=>x.trim()).filter(Boolean).forEach(t=>{if(!searchTags.some(x=>norm(x)===norm(t)))searchTags.push(t)});i.value="";render()}
function renderPurposeTags(){const c=el("purposeTags");c.replaceChildren();purposeTags.forEach((t,i)=>c.append(makeRemovableChip(t,()=>{purposeTags.splice(i,1);renderPurposeTags()})));el("purposeError").hidden=!!purposeTags.length}function addPurposeTag(){const i=el("purposeInput");i.value.split(/[,，／/、]+/).map(x=>x.trim()).filter(Boolean).forEach(t=>{if(!purposeTags.some(x=>norm(x)===norm(t)))purposeTags.push(t)});i.value="";renderPurposeTags()}
function render(){const f=keys.filter(k=>matches(k)&&(activeFilter==="all"||(activeFilter==="borrowed")===k.borrowed));grid.replaceChildren();f.forEach(k=>grid.append(createCard(k)));renderSearchTags();el("totalCount").textContent=keys.length;el("availableCount").textContent=keys.filter(k=>!k.borrowed).length;el("borrowedCount").textContent=keys.filter(k=>k.borrowed).length;el("resultNote").textContent=searchTags.length||activeFilter!=="all"?`找到 ${f.length} 項相符紀錄`:`現有 ${keys.length} 項鎖匙紀錄`;el("emptyState").hidden=!!f.length}
function addDataChips(target,values){values.forEach(v=>{const s=document.createElement("span");s.className="data-chip";s.textContent=v;target.append(s)})}
function createCard(k){const c=template.content.firstElementChild.cloneNode(true);c.classList.toggle("is-borrowed",k.borrowed);c.querySelector(".color-dot").style.background=colorMap[k.color]||colorMap.無;c.querySelector(".building").textContent=`${k.building} 大樓`;c.querySelector(".block-name").textContent=`· ${k.block}`;c.querySelector(".number").textContent=k.number;c.querySelector(".status-pill").textContent=k.borrowed?"已借出":"未借出";addDataChips(c.querySelector(".purpose-list"),k.purposes);addDataChips(c.querySelector(".floor-list"),k.floors);const b=c.querySelector(".status-action");b.textContent=k.borrowed?"✓ 標記為已歸還":"→ 標記為已借出";b.classList.add(k.borrowed?"btn-success":"btn-warning");b.onclick=()=>{k.borrowed=!k.borrowed;saveKeys();render()};c.querySelector(".edit-action").onclick=()=>openForm(k);c.querySelector(".delete-action").onclick=()=>confirmDelete(k);return c}
function buildFloorOptions(selected=[]){const c=el("floorOptions");c.replaceChildren();FLOOR_TAGS.forEach(f=>{const l=document.createElement("label");l.className="floor-tag";const i=document.createElement("input");i.type="checkbox";i.value=f;i.checked=selected.includes(f);i.onchange=()=>{const a=[...c.querySelectorAll("input")];if(f==="通匙"&&i.checked)a.filter(x=>x!==i).forEach(x=>x.checked=false);if(f!=="通匙"&&i.checked)a.find(x=>x.value==="通匙").checked=false;updateFloorStyles();el("floorError").hidden=true};l.append(i,document.createTextNode(f));c.append(l)});updateFloorStyles()}function updateFloorStyles(){document.querySelectorAll(".floor-tag").forEach(l=>l.classList.toggle("selected",l.querySelector("input").checked))}function selectedFloors(){return[...el("floorOptions").querySelectorAll("input:checked")].map(i=>i.value)}
function openForm(k=null){el("dialogTitle").textContent=k?"編輯鎖匙":"新增鎖匙";el("keyId").value=k?.id||"";el("tagColor").value=k?.color||"黑色";el("keyNumber").value=k?.number||"";el("building").value=k?.building||"";el("block").value=["Core 1","Core 2"].includes(k?.block)?k.block:"無";purposeTags=[...(k?.purposes||[])];renderPurposeTags();buildFloorOptions(k?.floors||[]);el("floorError").hidden=true;dialog.showModal();setTimeout(()=>el("keyNumber").focus(),0)}function closeForm(){dialog.close();form.reset();purposeTags=[]}
function confirmDelete(k){const d=el("confirmDialog");el("confirmText").textContent=`將刪除 ${k.building} 大樓 ${k.block} #${k.number}。此動作無法還原。`;d.showModal();d.addEventListener("close",()=>{if(d.returnValue==="confirm"){keys=keys.filter(x=>x.id!==k.id);saveKeys();render()}},{once:true})}
form.addEventListener("submit",e=>{e.preventDefault();if(el("purposeInput").value.trim())addPurposeTag();if(!form.reportValidity())return;const floors=selectedFloors();if(!purposeTags.length){el("purposeError").hidden=false;return}if(!floors.length){el("floorError").hidden=false;return}const id=el("keyId").value,current=keys.find(k=>k.id===id),r={id:id||crypto.randomUUID(),color:el("tagColor").value,number:el("keyNumber").value.trim(),purposes:[...purposeTags],building:el("building").value,block:el("block").value.trim(),floors,borrowed:current?.borrowed||false};keys=current?keys.map(k=>k.id===id?r:k):[r,...keys];saveKeys();closeForm();render()});
el("searchInput").addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===","){e.preventDefault();addSearchTag()}else if(e.key==="Backspace"&&!e.currentTarget.value&&searchTags.length){searchTags.pop();render()}});el("purposeInput").addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===","){e.preventDefault();addPurposeTag()}else if(e.key==="Backspace"&&!e.currentTarget.value&&purposeTags.length){purposeTags.pop();renderPurposeTags()}});el("purposeInput").addEventListener("blur",()=>{if(el("purposeInput").value.trim())addPurposeTag()});el("addKeyBtn").onclick=()=>openForm();el("closeDialogBtn").onclick=closeForm;el("cancelBtn").onclick=closeForm;el("clearSearch").onclick=()=>{searchTags=[];render()};document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));render()});render();
